CREATE
DATABASE IF NOT EXISTS `erp-crm-master` DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE
DATABASE IF NOT EXISTS `ryt_nelub7xr` DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE
DATABASE IF NOT EXISTS `ryt_5rbg03bp` DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
